name: Update GitHub Activity README

on:
  schedule:
    - cron: "0 */1 * * *" # Runs every 1 hour
  workflow_dispatch:

jobs:
  build:
    name: Update readme with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Update README with the recent activity."
          MAX_LINES: 5
